[tool.poetry]
name = "weather"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "2.25.1"
aiohttp = "3.8.4"
aiosignal = "1.3.1"
async-timeout = "4.0.2"
attrs = "22.2.0"
babel = "2.9.1"
certifi = "2022.12.7"
charset-normalizer = "3.0.1"
datetime = "5.0"
frozenlist = "1.3.3"
geographiclib = "2.0"
geopy = "2.3.0"
idna = "3.4"
magic-filter = "1.0.9"
multidict = "6.0.4"
pytz = "2022.7.1"
urllib3 = "1.26.14"
yarl = "1.8.2"
zope-interface = "5.5.2"
grequests = "^0.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
